baseURL = "https://ulampinoy.com/"
languageCode = "en-us"
title = "Ulampinoy Atbp."

 [[menu.main]]

 [[menu.main]]
  name = "About"
  url  = "/about/"
  weight = 0

 [[menu.main]]
  name = "Blog"
  url  = "/posts/"
  weight = 5